# Generated by Django 4.2 on 2023-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="addvehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=100)),
                ("car_plate", models.CharField(max_length=6)),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_contact", models.IntegerField(default=0, max_length=11)),
                ("parking_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
