# Generated by Django 4.2 on 2023-12-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_addvehicle_driver_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addvehicle",
            name="parking_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
