# Generated by Django 4.2 on 2023-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_addvehicle_parking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addvehicle",
            name="parking_time",
            field=models.CharField(max_length=100),
        ),
    ]
